#!/bin/bash

function varfunc1 {
    myvar="a"
}


function varfunc2 {
    echo "myvar in varfunc2: ${myvar}"
    echo "myvar1: ${myvar1}"
}

echo "Running vartest"
#echo "myvar: ${myvar}"
varfunc1
echo "myvar: ${myvar}"
myvar1="b"
varfunc2
echo "myvar: ${myvar}"

